name: Deploy Ghost CMS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Cache Terraform state
        uses: actions/cache@v4
        with:
          path: |
            terraform.tfstate
            terraform.tfstate.backup
          key: ${{ runner.os }}-ghostcms-tfstate
          restore-keys: |
            ${{ runner.os }}-ghostcms-

      - name: Terraform Init
        run: terraform -chdir=terraform init
      

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve -var="key_name=${{ secrets.AWS_KEY_NAME }}"
